### ISSUE TITLE
stop button not working for blinds

### ISSUE THREAD

**Issue by jfsant29** [Xorfor/Domoticz-API#1]
in device.py add this 2 lines 'SWITCH_STOP'👍 
    # Parameters used for: setcolbrightnessvalue
    SWITCH_ON = "On"
    SWITCH_OFF = "Off"
    **SWITCH_STOP = "Stop"**
    SWITCH_TOGGLE = "Toggle"
    SWITCH_SET_LEVEL = "Set Level"
    SWITCH_LIGHT_VALUES = {
        SWITCH_ON,
        SWITCH_OFF,
        **SWITCH_STOP,**
        SWITCH_TOGGLE,
    }

**Comment by Xorfor** [comment]
These switchvalues are used for 'switchlight' (not for 'setcolbrightnessvalue' as indicated is the comment line). I have to look in the Domoticz code, the json/api is not very well documented and a lot of values are hardcoded. I want to make a more generic interface to the devices. So I have to find out when a device is a blind.
My first guess is that a new function is required `is_blind` and depending on this, the `update_switch` method should be extended.

How do you want to use this value?

**Comment by jfsant29** [comment]
Creating a new function _is_blind_ is a good idea because
- switchlight use  On, Off, Toggle, SetLevel
- Blind use On/Close, Off/Open, Stop, SetLevel
Blinds are identified in Domoticz with SwitchType = "Blinds" or Type = "Blinds"

but adding Switch_stop as i indicated is working for me.
