### ISSUE TITLE
Device search by name hang in plugin

### ISSUE THREAD

**Issue by jfsant29** [Xorfor/Domoticz-API#4]
When I use DomoticzAPI.Device(server, name = "my device") in a plugin Domoticz hangs and must be restarted. When I use it in a normal python py, it works.

**Comment by Xorfor** [comment]
Do you have an example? Where did you use it in a Domoticz plugin?

**Comment by Xorfor** [comment]
Used example/plugin_2.py as test. Instead of idx, I used de name of the device, and still working!
