### ISSUE TITLE
Listing all devices fails ?

### ISSUE THREAD

**Issue by laurentlemercier** [Xorfor/Domoticz-API#6]
Hi
 
First of all : Many thanks to you for your work !

I try to enumerate all devices from a python script. using the following : 
```python
    server2 = DomoticzAPI.Server('192.168.1.122', '8081')
    devices = DomoticzAPI.Device(server2, idx=None, typename='devices')
```

If the above call is right, then I think the code inside device.py needs to be completed at line 170 to 173 in order to deal with the typename case (cf pull request #7) : 
```python
        elif self._name is not None:
            # Get all devices: /json.htm?type=devices&displayhidden=1
            querystring = "type={}&displayhidden=1".format(
                self._type_devices)
        elif self._typename is not None: 
            # Get all devices: /json.htm?type=devices&displayhidden=1
            querystring = "type={}&displayhidden=1".format(
                self._type_devices) 
        else:
            querystring = ""
```

Do you share my point of view (or am I missing something) ? 

Regards

Laurent

**Comment by Xorfor** [comment]
I merged your pull request. Looks good. Thnx!
