### ISSUE TITLE
Mishandle of existing hardware

### ISSUE THREAD

**Issue by laurentlemercier** [Xorfor/Domoticz-API#9]
Hello

When a hardware already exists (same name and type), the actual code recreates another one.

Sample code :

    server = dom.Server('192.168.1.122', '8081')
    hw2 = dom.Hardware(server,
                       type=dom.HTYPE_DUMMY,
                       port=1,
                       name="Test API hw2",
                       enabled="true")
    print("{}: {} - {} - {}".format(hw2, server.api.status, server.api.title, hw2.exists()))
    if hw2.exists():
        print("{}: {} - {} - {}".format(hw2, server.api.status, server.api.title, hw2.exists()))
    else:
        hw2.add()
        print("{}: {} - {} - {}".format(hw2, server.api.status, server.api.title, hw2.exists()))

The problem seems to come from __init__ and _init_ methods.  When Name and Type are provided, if the the corresponding hardware already exists, the idx is not evaluated and exists function always returns false.  Pull request #7 tries to correct this.

Regards

Laurent

**Comment by Xorfor** [comment]
I merged your pull request. Thnx!
